all:
  vars:
    # GKE cluster variables
    gcp_project: ascn-440621                          # ID of GCP Project
    gcp_auth_kind: serviceaccount                     # Do not change
    gcp_cred_file: ascn-440621-key.json               # Path to service account keys (json file downloaded from GCP)

    gcp_zone: us-central1-a
    gcp_image_type: ubuntu_containerd
    # gcp_machine_type: e2-small                      # 2 vCPUs, 2 GB de mem贸ria
    gcp_machine_type: e2-standard-2                   # 2 vCPUs, 8 GB de mem贸ria
    # gcp_machine_type: e2-standard-4                 # 4 vCPUs, 16 GB de mem贸ria
    # gcp_machine_type: e2-standard-8                 # 8 vCPUs, 32 GB de mem贸ria
    gcp_disk_size_gb: 100                             # Can be changed if necessary
    gcp_initial_node_count: 3                         # Number of nodes to create. Can be changed if necessary

    # BEGIN Test variables (DO NOT CHANGE)
    app_notifier_email: notifier@moonshot.pt
    app_notifier_password: 123456
    result_code: 200
    dgc_uvci: 01-PT-REF03A4F19045CC0446C0814903DBC33B5DE84-9
    # END Test variables (DO NOT CHANGE)

    # APP variables
    app_ip: '34.57.170.250'
    app_port: 30007

    # Prometheus Node Exporter Variables
    node_exporter_ip: '34.118.230.31'
    node_exporter_port: 9100

    # Load VMs
    load_vms: 5
    load_vm_machine_type: e2-small
    load_vm_image_project: ubuntu-os-cloud
    load_vm_image: ubuntu-2004-focal-v20241219
    load_vm_zone: us-central1-a
    load_vm_label: load

    # User of load VMs
    ansible_user: ansible

    # Tests specification
    local_load_test: tests/
    local_load_test_output: tests/output/
    local_load_test_dashboard: tests/dashboard/

    remote_load_test: /home/tests/
    remote_load_test_input: /home/tests/input/
    remote_load_test_output: /home/tests/output/
    remote_load_test_dashboard: /home/tests/dashboard/

    jmeter_load_test_file: load_app.jmx
    jmeter_load_test_threads: 100
    jmeter_load_test_iters: 100

    k6_load_test_file: load_app.js
    k6_load_test_vus: 100
    k6_load_test_iters: 3000

    # Moonshot deployment hpa
    moonshot_hpa: "true"
    moonshot_min_reps: 1
    moonshot_max_reps: 5

    # Seed database when deploy
    seed_database: "false"

    # Delete data when undeploy
    delete_data: "false"

    # Docker images
    db_image: postgres:15.4
    moonshot_image: digoquedigo/moonshot:latest

    # PVC variables
    pvc_name: postgres-pvc

    # Database variables
    db_name: moonshot
    db_host: postgres-service
    db_username: admin
    db_password: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              38663064646534626532313335363139353766373932663561363963343232616530616433363466
              6532666433396164623735353161323462353831646539630a613436643737616235393438616438
              31646638653764376338616466383063613531303334653733346336333766346439366263653465
              6365356236356439640a346337306463386133643634613237343339353236653563623061613439
              3165