---
- name: Undeploy the Grafana Deployment
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/grafana/grafana-deployment.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Undeploy the Grafana Service
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/grafana/grafana-service.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Undeploy the Grafana PVC
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/grafana/grafana-pvc.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Delete Grafana namespace
  kubernetes.core.k8s:
    state: absent
    kind: namespace
    name: grafana
    wait: true
    wait_timeout: 120