---
apiVersion: v1
kind: Service
metadata:
  name: moonshot-service
  namespace: default
  labels:
    app: moonshot
spec:
  type: LoadBalancer
  selector:
    app: moonshot
  ports:
    - name: http
      protocol: TCP
      targetPort: 8000
      port: 30007