---
- name: Delete ConfigMap of Moonshot
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/moonshot/moonshot-config.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Delete Secret of Moonshot
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/moonshot/moonshot-secret.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Undeploy the Moonshot Deployment
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/moonshot/moonshot-deployment.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Undeploy the Moonshot Service
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/moonshot/moonshot-service.yml') | from_yaml }}"
    wait: true
    wait_timeout: 120

- name: Delete Horizontal Pod Autoscaler of Moonshot Deployment
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'templates/moonshot/moonshot-hpa.yml') }}"
    wait: true
    wait_timeout: 120
  when: moonshot_hpa == "true"