---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ pvc_name }}"
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: stc-postgres
  resources:
    requests:
      storage: 20Gi