---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  POSTGRES_DB: "{{ db_name }}"
  POSTGRES_USER: "{{ db_username }}"
  PGDATA: /var/lib/postgresql/data/pgdata