---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stc-postgres
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true