apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-scrape-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['{{ node_exporter_ip }}:{{ node_exporter_port }}']